[package]
name = "hyprland"
version = "0.2.4"
edition = "2021"
authors = ["yavko <yavornkolev@gmail.com>"]
license = "GPL-3.0-or-later"
keywords = ["hyprland", "ipc", "hypr", "wayland", "linux"]
categories = ["api-bindings"]
readme = "README.md"
description = "A unoffical rust wrapper for hyprland's IPC"
homepage = "https://github.com/yavko/hyprland-rs"
repository = "https://github.com/yavko/hyprland-rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
opt-level = "z"
strip = true
lto = true

[dev-dependencies]
rusty-hook = "^0.11.2"

[dependencies]
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
serde_repr = "0.1"
hex = "0.4"
tokio = { version = "1.20", features = ["full"] }
lazy_static = "1.4"
regex = "1.6"
