[package]
name = "hyprland"
version = "0.3.0"
edition = "2021"
authors = ["yavko <yavornkolev@gmail.com>"]
license = "GPL-3.0-or-later"
keywords = ["hyprland", "ipc", "hypr", "wayland", "linux"]
categories = ["api-bindings"]
readme = "README.md"
description = "A unoffical rust wrapper for hyprland's IPC"
homepage = "https://github.com/hyprland-community/hyprland-rs"
repository = "https://github.com/hyprland-community/hyprland-rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package.metadata.nix]
#app = true
build = true
#library = true
#systems = [
#    "aarch64-linux",
#    "i686-linux",
#    "x86_64-linux",
#]

[profile.release]
opt-level = "z"
strip = true
lto = true

[dev-dependencies]
rusty-hook = "0.11.*"

[dependencies]
serde = {version = "1", features = ["derive"]}
serde_json = "1"
serde_repr = "0.1"
hex = "0.4"
tokio = { version = "1", features = ["full"] }
lazy_static = "1.4"
regex = "1.6"
async-trait = "0.1"

[features]
default = ["listener", "dispatch", "data", "keyword"]
dispatch = []
data = []
keyword = []
listener = ["data", "dispatch"]

