[package]
name = "hyprland"
version = "0.3.0"
edition = "2021"
authors = ["yavko <yavornkolev@gmail.com>"]
license = "GPL-3.0-or-later"
keywords = ["hyprland", "ipc", "hypr", "wayland", "linux"]
categories = ["api-bindings"]
readme = "README.md"
description = "A unoffical rust wrapper for hyprland's IPC"
homepage = "https://github.com/hyprland-community/hyprland-rs"
repository = "https://github.com/hyprland-community/hyprland-rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package.metadata.nix]
build = true

[profile.release]
opt-level = "z"
strip = true
lto = true

[dependencies]
serde = {version = "1", features = ["derive"]}
serde_json = "1"
serde_repr = "0.1"
hex = "0.4"
tokio = { version = "1", features = ["full"], optional = true }
async-net = { version = "1", optional = true }
async-std = { version = "1", optional = true }
futures-lite = { version = "1", optional = true }
lazy_static = "1.4"
regex = "1.6"
async-trait = "0.1"
num-traits = "0.2"
doc-comment = "0.3"
paste = "1"
strum = "0.24"
strum_macros = "0.24"


[features]
default = ["listener", "dispatch", "data", "keyword", "config", "tokio"]
async-net = ["dep:async-net", "dep:futures-lite"]
async-std = ["dep:async-std", "dep:futures-lite"]
tokio = ["dep:tokio"]
dispatch = []
data = []
keyword = []
config = ["dispatch", "keyword"]
listener = ["data", "dispatch"]

