[package]
name = "hyprland-macros"
version = "0.1.0"
edition = "2021"

[package.metadata.nix]
build = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
syn = "2"
quote = "1"
